version: '3.8'

services:
  db:
    image: mysql:latest
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: 'testweb_db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=testWeb.settings
      - SQL_ENGINE=django.db.backends.mysql
      - SQL_DATABASE=testweb_db
      - SQL_USER=root
      - SQL_PASSWORD=password
      - SQL_HOST=db
      - SQL_PORT=3306
      - DATABASE=mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
